### ISSUE TITLE
Error importing JK III:JA map

### ISSUE THREAD

**Issue by Snyper1701** [SomaZ/Blender_BSP_Importer#28]
after unpacking all .pk3 and installing the plugin on blender 2.83 I get this error when I try to import a map. 
![Error](https://user-images.githubusercontent.com/81515069/129269683-7d3ed996-5806-4665-8f09-c88cd80b3631.png)

further information:
- unpacked at c:/desktop in a folder called JKIII
- this folder is also set as the base folder in blender plug in preferences.
- JKIII is the Steam-Version
- After import, only the props are getting importet. 

feel free to ask, if you need more information. Thank you in advance

**Comment by SomaZ** [comment]
Oh hey, thank you for reporting an issue here.

The error comes from a change in blenders material system between 2.82 and 2.83 iirc. This is something that I fixed long time ago. I just haven't gotten around making a new release. If you get the lastest code from the main branch and pack it into a zip, and install it, then it should work just fine in blender 2.83. Though I haven't tested the addon in 2.83 for quite a while now. Currently working in 2.93. You can get a packed version of the latest addon here:
https://trello.com/c/aMEbgAXC
I will upload a new release here on github when version 1.0 is finished.

If the issue is not resolved, please feel free to reopen it.
