### ISSUE TITLE
When importing bsp files from Star trek elite force

### ISSUE THREAD

**Issue by JHstrutton2000** [SomaZ/Blender_BSP_Importer#30]
the first import runs fine but if you don't close and then reopen then the second import is just the first import with a few of the second's meshes.

**Comment by SomaZ** [comment]
Yea, this is not related to a game specifically. Opening a new file works fine, no need to close and reopen blender completely.

The reason for this to happen is that the addon creates meshes and objects. The objects refere to entities. The meshes are the actual geometry data. The addon imports bsp models as meshes and names them based on the bsp name. If you dont delete the meshes after deleting all your objects, they are still present in your scene. The next import will reuse the models from first import (because they are still stored in the scene) and so it will look like it didnt import the new bsp properly. Even though the addon probably did import everything properly, it just messed up finding the new meshes. If you open the "Object Data Properties" tab and change the obeject data to the next one with the same name with an appended ".001" it will show you the correct mesh of the second import. It's not a solution, I know. Just for clarifying the problem. Will add a fix to the next version. Untill then, open a new file and reimport into that instead.

**Comment by SomaZ** [comment]
Should be fixed with https://github.com/SomaZ/Blender_BSP_Importer/commit/83c5b2f0ea8a937e04ffae2f349e5bcf226d1789
Let me know if you still run into issues and feel free to reopen this again if so. Thanks for the report.
