### ISSUE TITLE
Cannot instal the addon

### ISSUE THREAD

**Issue by Hrofti** [SomaZ/Blender_BSP_Importer#40]
For some reason, I cannot install the addon for Blender version 4.2.1. Screen attached. And my friend too cannot do this. 
I clicked Code - Download ZIP
![2024-09-18_17-45-06](https://github.com/user-attachments/assets/4cdce075-ddf5-4347-a7cc-bd5c7d5b6c10)

**Comment by SomaZ** [comment]
You have to get the zip file from the releases page. [Release v0.9.96](https://github.com/SomaZ/Blender_BSP_Importer/releases/tag/v0.9.96)
Direct downloads of the code won't work as an addon because theres folder nesting which prevents blender to "see" the actual addon. If you need the latest latest code, extract the zip file you downloaded. In there, theres a folder. Open it, zip the "import_bsp" folder including all its content into a new zip file. This new zip file can be installed.
